# Generated by Django 6.0.2 on 2026-03-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("week2", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Products",
        ),
    ]
