# Generated by Django 6.0.2 on 2026-03-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("week2", "0002_rename_product_products"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
